#include "movegen/magics.h"

#include <bit>

#include "movegen/attacks.h"

Magic rook_magics[64];
Magic bishop_magics[64];

namespace {

// The two shared "fancy magic" tables. Each square gets a slice sized to its own
// mask rather than a uniform worst-case block, which is what keeps the rook
// table at 800 KiB instead of the 4 MiB a flat 64 x 4096 array would cost.
// The totals are derived from the masks, so a mask change cannot silently
// overflow them.
constexpr int table_size(Bitboard (*relevant_mask)(int)) {
	int total = 0;
	for (int square = 0; square < 64; square++) total += 1 << std::popcount(relevant_mask(square));
	return total;
}

constexpr int kRookTableSize = table_size(rook_relevant_mask);	  // 102,400 entries, 800 KiB
constexpr int kBishopTableSize = table_size(bishop_relevant_mask); // 5,248 entries, 41 KiB

Bitboard rook_table[kRookTableSize];
Bitboard bishop_table[kBishopTableSize];

// Fills one square's slice by walking every subset of its mask. The
// subtract-and-mask step is the carry-rippler: borrowing from `mask` propagates
// only through bits `mask` has set, so the sequence visits each of the 2^bits
// subsets exactly once and returns to zero.
void init_square(Magic& m, int square, Bitboard mask, Bitboard magic, Bitboard* slice,
                 Bitboard (*reference)(Square, Bitboard)) {
	m.mask = mask;
	m.magic = magic;
	m.shift = static_cast<unsigned>(64 - std::popcount(mask));
	m.attacks = slice;

	Bitboard occupied = 0;
	do {
		slice[m.index(occupied)] = reference(static_cast<Square>(square), occupied);
		occupied = (occupied - mask) & mask;
	} while (occupied);
}

}  // namespace

void init_magics() {
	int rook_offset = 0;
	int bishop_offset = 0;

	for (int square = 0; square < 64; square++) {
		const Bitboard rook_mask = rook_relevant_mask(square);
		init_square(rook_magics[square], square, rook_mask, rook_magic_numbers[square],
		            rook_table + rook_offset, ray_rook_attacks);
		rook_offset += 1 << std::popcount(rook_mask);

		const Bitboard bishop_mask = bishop_relevant_mask(square);
		init_square(bishop_magics[square], square, bishop_mask, bishop_magic_numbers[square],
		            bishop_table + bishop_offset, ray_bishop_attacks);
		bishop_offset += 1 << std::popcount(bishop_mask);
	}
}

// Generated by tools/magicgen and checked in rather than searched at startup: a
// startup cost that varies run to run is not one an engine should carry, and 128
// values that decide the correctness of every sliding move belong somewhere a
// diff can see them. See docs/adr/0007-magic-bitboards.md.
// Reproduce with:  ./build/release/tools/magicgen/dahlia_magicgen --seed 0
const Bitboard rook_magic_numbers[64] = {
	0x038004801120C004ULL,
	0x08C0004020011000ULL,
	0x0200082080420010ULL,
	0x0080080010008006ULL,
	0x46001020040A0028ULL,
	0x2100080400010002ULL,
	0x1200080082000104ULL,
	0x0100002200508100ULL,
	0x1010800040008030ULL,
	0x0044804000802004ULL,
	0x0001002008110040ULL,
	0x0485001001010C20ULL,
	0x2820808004000800ULL,
	0x0002808004002200ULL,
	0x0001000100040200ULL,
	0x0414800080004100ULL,
	0x088000C000200041ULL,
	0x4420808020004008ULL,
	0x2010012004002800ULL,
	0x0000220042000810ULL,
	0x0001828008000400ULL,
	0xA000880120100440ULL,
	0x105434000810010AULL,
	0x0002060000428324ULL,
	0x0080822480044000ULL,
	0x0240080020100020ULL,
	0x4080100080802000ULL,
	0x0000100080080084ULL,
	0x0000080080800400ULL,
	0x0006000600181014ULL,
	0x0004010400021008ULL,
	0x1000011A0002C284ULL,
	0x0240284000800881ULL,
	0x0010002001400050ULL,
	0x0000100080802000ULL,
	0x0010004400400800ULL,
	0x0206000422001008ULL,
	0x4010800400800200ULL,
	0x0002004426001829ULL,
	0x0000408106000A44ULL,
	0x1000400220818000ULL,
	0xA410004020004000ULL,
	0x1529001220010040ULL,
	0x0708000810008080ULL,
	0x0010080100050010ULL,
	0x1E40020004008080ULL,
	0x0000419210140048ULL,
	0x0881886485120004ULL,
	0x0010482080010500ULL,
	0x4080400020100040ULL,
	0x0004200041081100ULL,
	0xAC00801000080080ULL,
	0x0201008020401002ULL,
	0x0060040002008080ULL,
	0x2905100802010400ULL,
	0x0048145504008200ULL,
	0x0219024200802212ULL,
	0x0A20E58242003102ULL,
	0x80010010A0008C41ULL,
	0x0801000420081001ULL,
	0xC001001042080045ULL,
	0x9021000400020801ULL,
	0x0409000082000441ULL,
	0x4820004400248502ULL,
};

const Bitboard bishop_magic_numbers[64] = {
	0x2082208200810101ULL,
	0x1048022404202830ULL,
	0x0110040040480002ULL,
	0x401089020008CC00ULL,
	0x0002021060101000ULL,
	0x081A0E0A20000420ULL,
	0x2020821010048008ULL,
	0x0640402401084041ULL,
	0x4000410304010201ULL,
	0x1820204800890440ULL,
	0x0200180644002400ULL,
	0x04010440508000A0ULL,
	0x0000020211000400ULL,
	0x0820220202201000ULL,
	0x0000818648201400ULL,
	0x0003182A01042010ULL,
	0x0021000848911800ULL,
	0x40440023080A0414ULL,
	0x0008000400501202ULL,
	0x0808240104010000ULL,
	0x0285000090400010ULL,
	0x004200B408840440ULL,
	0x4802A10600842040ULL,
	0x0000821020880880ULL,
	0x801030C4400C6500ULL,
	0x00280480A0842080ULL,
	0x200C0840040A4402ULL,
	0x0000802008020020ULL,
	0x0112002102008041ULL,
	0x00D4420041009210ULL,
	0x1005140603040180ULL,
	0x0004208180404400ULL,
	0x0001044010101000ULL,
	0x4448081440023480ULL,
	0x2002008200C05200ULL,
	0x0C00020080080080ULL,
	0x2404040400121010ULL,
	0x2010100040008043ULL,
	0x0003842500040500ULL,
	0x0021010100002405ULL,
	0x8008410410022000ULL,
	0xD000841042000820ULL,
	0x0020601350000800ULL,
	0x0000284010400A00ULL,
	0x2220A00820829010ULL,
	0x001045100F004022ULL,
	0x0102048114053200ULL,
	0x111009120C840820ULL,
	0x0A0A009024108544ULL,
	0x00020A0101090000ULL,
	0x0000548608160280ULL,
	0x0100400020880000ULL,
	0x2200000903040200ULL,
	0x0004048810810840ULL,
	0x035020D204006012ULL,
	0x4BD0100101042484ULL,
	0x4000210802016082ULL,
	0x0030302208040404ULL,
	0xA000000200840480ULL,
	0x0201040200840400ULL,
	0x0018000440B04440ULL,
	0x0000800490220200ULL,
	0x9011082004208203ULL,
	0x0620222400440440ULL,
};
